haveTrouble={
'sorry sir, i dont understand',
'can you repeat please?',
'my bad sir, can you repeat?',
'i did not listen to you sir',
"Apologies, sir. Can you repeat that?",
"My mistake, sir. Could you say that again?",
"Sorry, sir. Can you repeat what you just said?",
"I goofed. Can you repeat that, sir?",
"My fault, sir. Could you please repeat?",
"I messed up. Can you say that again, sir?",
"Apologies, sir. Mind repeating that for me?",
"Oops, my bad. Can you say it one more time, sir?",
"My mistake, sir. Can you repeat for clarity?",
"Sorry about that. Can you please repeat, sir?",
"My apologies, sir. Repeat, please?",
"I misunderstood. Can you say that again, sir?",
"I messed that up. Can you repeat, sir?",
"I misheard. Can you say that again, sir?",
"Sorry for the confusion. Can you repeat, sir?",
"My bad, sir. Repeat that, please?",
"I misspoke. Can you say it again, sir?",
"Apologies, sir. Mind repeating that?",
"I didn't catch that. Can you repeat, sir?",
"My mistake, sir. Can you say it once more?",
"I misunderstood. Can you repeat that, sir?",
"I'm sorry, sir. Can you say that again?",
"My bad. Could you repeat, sir?",
"Apologies, sir. Repeat, please?",
"I messed up. Can you say it again, sir?",
"I misunderstood. Can you repeat, sir?",
"Sorry about that. Can you repeat, sir?",
"My fault. Can you say that again, sir?",
"I goofed. Can you repeat, please, sir?",
"I didn't catch that. Can you say it again, sir?",
"My apologies, sir. Repeat that for me?",
"I misspoke. Can you say that again, sir?",
"I misunderstood. Can you repeat that, sir?",
"My bad, sir. Could you repeat that, please?",
"Sorry for the confusion. Can you repeat, sir?",
"Apologies, sir. Mind repeating that for me?",
"I didn't catch that. Can you repeat, sir?",
"My mistake, sir. Can you say it once more?",
"I messed up. Can you repeat that, sir?",
"My apologies, sir. Repeat, please?",
"I'm sorry, sir. Can you say that again?",
"My bad. Could you repeat, sir?",
"Apologies, sir. Repeat, please?",
"I messed up. Can you say it again, sir?",
"I misunderstood. Can you repeat, sir?",
"Sorry about that. Can you repeat, sir?",
"My fault. Can you say that again, sir?",
"I goofed. Can you repeat, please, sir?",
"I didn't catch that. Can you say it again, sir?"

}