hello={"yes sir",
    "Hi there",
    "what can i help you",
    "Yes, tell me",
    "yes, at your service",
    "yes, I am Here",
    "How can I help?",
    "Need assistance?",
    "Can I assist?",
    "What's up?",
    "Any questions?",
    "Here to help.",
    "Need support?",
    "What's on your mind?",
    "How can I assist you?",
    "What do you need?",
     "Go ahead, I'm listening.",
    "Sure, what do you need?",
    "Absolutely, share with me.",
    "Yes, what's on your mind?",
    "Of course, tell me more.",
    "Ready to hear, go ahead.",
    "Yes, what can I do for you?",
    "Sure thing, tell me.",
    "Absolutely, I'm listening.",
    "Yes, what's up?"
}