thomaslisten={"sorry sir, need something?",
    "need something?",
    "my bad sir, can you repeat?",
    "if you need me just call me by my name",
    "need me sir?",
    "Could you please repeat that?",
    "I'm sorry, I didn't catch that. Can you say it again?",
    "I missed what you just said. Could you repeat it?",
    "Pardon me, but I didn't quite hear you. Can you repeat that?",
    "I didn't understand. Can you say that one more time?",
    "I'm having trouble hearing you. Could you repeat yourself?",
    "I didn't get that. Can you say it again, please?",
    "Sorry, I didn't hear you clearly. Could you repeat your statement?",
    "Excuse me, I need you to say that again.",
    "Could you kindly repeat what you just said?",
    "I didn't catch your words. Can you repeat them for me?",
    "I missed that. Can you repeat it, please?",
    "I didn't hear the last part. Can you repeat it?",
    "I'm sorry, but I didn't hear you well. Could you repeat that?",
    "Can you run that by me one more time?",
    "I didn't quite catch that. Can you repeat yourself?",
    "Sorry, I didn't get that. Can you repeat it, please?",
    "I didn't hear what you said. Could you say it again?",
    "Can you please repeat what you just mentioned?",
    "I missed a part of what you said. Could you repeat it?",
    "Could you say that again? I didn't hear you clearly.",
    "Sorry, I didn't catch your words. Can you repeat them?",
    "I didn't understand. Can you say that one more time?",
    "Pardon me, but I didn't quite hear you. Can you repeat that?",
    "I'm having trouble hearing you. Could you repeat yourself?",
    "I didn't get that. Can you say it again, please?",
    "Excuse me, I need you to say that again.",
    "Could you kindly repeat what you just said?",
    "I didn't catch your words. Can you repeat them for me?",
    "I missed that. Can you repeat it, please?",
    "I didn't hear the last part. Can you repeat it?",
    "I'm sorry, but I didn't hear you well. Could you repeat that?",
    "Can you run that by me one more time?",
    "I didn't quite catch that. Can you repeat yourself?",
    "Sorry, I didn't get that. Can you repeat it, please?",
    "I didn't hear what you said. Could you say it again?",
    "Can you please repeat what you just mentioned?",
    "I missed a part of what you said. Could you repeat it?",
    "Could you say that again? I didn't hear you clearly.",
    "Sorry, I didn't catch your words. Can you repeat them?",
    "I didn't understand. Can you say that one more time?",
    "Pardon me, but I didn't quite hear you. Can you repeat that?",
    "I'm having trouble hearing you. Could you repeat yourself?",
    "I didn't get that. Can you say it again, please?",
    "Excuse me, I need you to say that again.",
    "Could you kindly repeat what you just said?",
    "I didn't catch your words. Can you repeat them for me?",
    "I missed that. Can you repeat it, please?",
    "I didn't hear the last part. Can you repeat it?",
    "I'm sorry, but I didn't hear you well. Could you repeat that?"
}
